// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARoRz4mFfET76sO0uVQZJRZ8rI-EMGJE8',
    appId: '1:718904534981:web:d3d4f28cd4373820368dac',
    messagingSenderId: '718904534981',
    projectId: 'ridefix-9ca5c',
    authDomain: 'ridefix-9ca5c.firebaseapp.com',
    storageBucket: 'ridefix-9ca5c.firebasestorage.app',
    measurementId: 'G-6MP74Z2K8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc-BoP1Ubs7z7k6wmHs2xjua3-vVr24Xw',
    appId: '1:718904534981:android:a94c683f94cff75c368dac',
    messagingSenderId: '718904534981',
    projectId: 'ridefix-9ca5c',
    storageBucket: 'ridefix-9ca5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpwAzaIB47TuzOTuB3Fl1d47ZCtAYgiMY',
    appId: '1:718904534981:ios:c2555b6c4abb411b368dac',
    messagingSenderId: '718904534981',
    projectId: 'ridefix-9ca5c',
    storageBucket: 'ridefix-9ca5c.firebasestorage.app',
    iosBundleId: 'com.example.ridefix',
  );
}
